apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-app
  labels:
    app: kubernetes-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubernetes-app
  template:
    metadata:
      labels:
        app: kubernetes-app
    spec:
      containers:
      - name: kubernetes-jenkins-astrovilla
        image: 855978170589.dkr.ecr.ap-south-1.amazonaws.com/eks-app1:latest
        ports:
        - containerPort: 8010
        
