apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-cluster-app
  labels:
    app: eks-app1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eks-app1
  template:
    metadata:
      labels:
        app: eks-app1
    spec:
      containers:
      - name: eks-app1
        image: 855978170589.dkr.ecr.ap-south-1.amazonaws.com/eks-app1:latest
        ports:
        - containerPort: 8081
-------

apiVersion: v1
kind: Service
metadata:
  name: eks-cluster-app
spec:
  selector:
    app: eks-app1
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8081
    nodePort: 32111

