apiVersion: v1
kind: Service
metadata:
  name: kubernetes-app
spec:
  selector:
    app: kubernetes-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8010
    nodePort: 32110
